### ISSUE TITLE
Fail to scrape on HTTPS

### ISSUE THREAD

**Issue by StartloJ** [promhippie/jenkins_exporter#4]
Hi,
I have problem on running binary file with build from source code.

Host env: Linux 4.4.0-127-generic #153-Ubuntu x86_64 GNU/Linux
Error is following line:
<pre>
INFO[0000] Starting Jenkins exporter (version=, branch=, revision=)  source="main.go:57"
INFO[0000] Build context (go=go1.11.5, user=, date=)     source="main.go:58"
INFO[0000] Listening on :9103                            source="main.go:72"
DEBU[0004] start scrape loop                             source="exporter.go:84"
DEBU[0004] failed to request root api. Get https://x.x.x.x/api/json: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs  source="exporter.go:91"
ERRO[0004] failed to fetch root data                     source="exporter.go:67"
</pre>

what is my mistake and how can I do to solve

**Comment by tboerger** [comment]
I think the error is pretty obvious, use a valid domain name that is matching the SSL cert and it should be fine.
